<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-E225OPG" failures="1" tests="1" name="Create new user" time="11.659" errors="0" timestamp="28 Aug 2022 03:40:18 GMT">
  <testcase classname="APITests" name="createNewUser" time="11.605">
    <failure type="java.lang.AssertionError" message="expected [201] but found [422]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [422]
at APITests.createNewUser(APITests.java:47)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createNewUser -->
  <testcase classname="APITests" name="createUserWithoutBody" time="0.0">
    <ignored/>
  </testcase> <!-- createUserWithoutBody -->
  <testcase classname="APITests" name="createNewUserWithInvalidAuth" time="0.0">
    <ignored/>
  </testcase> <!-- createNewUserWithInvalidAuth -->
  <testcase classname="APITests" name="updateUser" time="0.0">
    <ignored/>
  </testcase> <!-- updateUser -->
  <testcase classname="APITests" name="deletingSameUserTwice" time="0.0">
    <ignored/>
  </testcase> <!-- deletingSameUserTwice -->
  <testcase classname="APITests" name="updateUserWithInvalidId" time="0.0">
    <ignored/>
  </testcase> <!-- updateUserWithInvalidId -->
  <testcase classname="APITests" name="deleteUser" time="0.0">
    <ignored/>
  </testcase> <!-- deleteUser -->
</testsuite> <!-- Create new user -->
